Repository fzxiao233/Auto_Record_Matsuri, pull requests merged in 2019-07, with the labels that each got.

#94 添加上传开关
  config.py
  run.py
Labels: enhancement

#98 修正主进程退出后子进程残留的问题
  LICENSE
  bilibili.py
  bilibili_api/bilibili_api.py
  daemon.py
  mirrativ.py
  openrec.py
  requirements.txt
  run.py
  twitcasting.py
  upload.py
  youtube.py
Labels: bug, enhancement

#102 新增上传重试，默认重试3次（三次都不成功估计也传不上去了，故不提供配置
  Dockerfile
  upload.py
Labels: enhancement

#103 修改重名为添加时间戳
  video_process.py
Labels: invalid

#104 加入画质设定
  config.py
  video_process.py
Labels: enhancement

#106 Add/multi database
  mirrativ.py
  openrec.py
  twitcasting.py
  upload.py
  users_map.py
  youtube.py
Labels: enhancement

#111 修改上传的实现方式
  daemon.py
  queues.py
  run.py
  video_process.py
Labels: enhancement

#113 修复了检测问题，改为通过IsLive 标签进行检测
  youtube.py
Labels: bug

#117 重构部分代码
  bilibili.py
  config_example.py
  daemon.py
  mirrativ.py
  openrec.py
  run.py
  tools.py
  twitcasting.py
  video_process.py
  youtube.py
Labels: enhancement

#119 修正logging
  upload.py
Labels: bug
